const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.custom,
		C3.Plugins.TiledBg,
		C3.Plugins.Shape3D,
		C3.Behaviors.solid,
		C3.Plugins.Camera3D,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Plugins.Particles,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Plugins.Button,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Camera3D.Acts.LookParallelToLayout,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Camera3D.Acts.SetPosition,
		C3.Plugins.Mouse.Cnds.OnMovement,
		C3.Plugins.Camera3D.Acts.RotateCamera,
		C3.Plugins.Mouse.Exps.MovementX,
		C3.Plugins.Mouse.Exps.MovementY,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Acts.RequestPointerLock,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Shape3D.Cnds.CompareInstanceVar,
		C3.Plugins.Shape3D.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Shape3D.Cnds.OnCollision,
		C3.Plugins.Shape3D.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Camera3D.Exps.CameraXRotation,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.custom.Acts.PushOutSolidAngle,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Shape3D.Acts.SetZElevation,
		C3.Plugins.Shape3D.Acts.SetAngle,
		C3.Plugins.Shape3D.Acts.SetInstanceVar,
		C3.Plugins.Camera3D.Exps.CameraYRotation,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Shape3D.Cnds.OnCreated,
		C3.Plugins.Shape3D.Acts.SetPos,
		C3.Plugins.Shape3D.Exps.X,
		C3.Plugins.Shape3D.Exps.Angle,
		C3.Plugins.Shape3D.Exps.Y,
		C3.Plugins.Shape3D.Exps.ZElevation,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.ResetEventVar
	];
};
self.C3_JsPropNameTable = [
	{Custom: 0},
	{player: 0},
	{stand: 0},
	{Solid: 0},
	{shape: 0},
	{"3DCamera": 0},
	{Mouse: 0},
	{Keyboard: 0},
	{wall: 0},
	{zAxis: 0},
	{speed: 0},
	{Bullet: 0},
	{bulletz: 0},
	{health: 0},
	{MoveTo: 0},
	{enemy: 0},
	{spawn_enemy: 0},
	{start: 0},
	{"3DShape": 0},
	{tembok: 0},
	{Sprite: 0},
	{"3DShape3": 0},
	{"3DShape4": 0},
	{Particles: 0},
	{Audio: 0},
	{Score: 0},
	{Text2: 0},
	{Text: 0},
	{defeat: 0},
	{InitialWidth: 0},
	{HealthBar: 0},
	{HealthBorder: 0},
	{victory: 0},
	{efek: 0},
	{Sprite2: 0},
	{getih: 0},
	{Rotate: 0},
	{add: 0},
	{Button: 0},
	{arrow1: 0},
	{Touch: 0},
	{arrow2: 0},
	{arrow3: 0},
	{arrow4: 0},
	{button1: 0},
	{"3DShape5": 0},
	{Sprite3: 0},
	{box: 0},
	{Box: 0},
	{kotak: 0},
	{of: 0},
	{Sprite4: 0},
	{menu: 0},
	{plus: 0},
	{Button2: 0},
	{play: 0},
	{menubg: 0},
	{restart: 0},
	{exit: 0},
	{loading: 0},
	{PlayerHeight: 0},
	{PlayerSpeed: 0},
	{MouseSpeed: 0},
	{Life: 0},
	{LifeMax: 0}
];

self.InstanceType = {
	player: class extends self.ISpriteInstance {},
	stand: class extends self.ITiledBackgroundInstance {},
	shape: class extends self.I3DShapeInstance {},
	_3DCamera: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	wall: class extends self.I3DShapeInstance {},
	bulletz: class extends self.I3DShapeInstance {},
	enemy: class extends self.I3DShapeInstance {},
	spawn_enemy: class extends self.ISpriteInstance {},
	start: class extends self.I3DShapeInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	tembok: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	_3DShape3: class extends self.I3DShapeInstance {},
	_3DShape4: class extends self.I3DShapeInstance {},
	Particles: class extends self.IParticlesInstance {},
	Audio: class extends self.IInstance {},
	Text2: class extends self.ITextInstance {},
	health: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	defeat: class extends self.ISpriteInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	HealthBorder: class extends self.ISpriteInstance {},
	victory: class extends self.ISpriteInstance {},
	efek: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	getih: class extends self.ISpriteInstance {},
	add: class extends self.I3DShapeInstance {},
	Button: class extends self.IButtonInstance {},
	arrow1: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	arrow2: class extends self.ISpriteInstance {},
	arrow3: class extends self.ISpriteInstance {},
	arrow4: class extends self.ISpriteInstance {},
	button1: class extends self.ISpriteInstance {},
	_3DShape5: class extends self.I3DShapeInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	box: class extends self.I3DShapeInstance {},
	kotak: class extends self.ITextInstance {},
	of: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	plus: class extends self.ISpriteInstance {},
	Button2: class extends self.IButtonInstance {},
	play: class extends self.ISpriteInstance {},
	menubg: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	exit: class extends self.ISpriteInstance {},
	loading: class extends self.ISpriteInstance {}
}